# 端口
server:
  port: 8089

  #  拦截路径
  servlet:
    path: /
#    日志级别
logging:
  level:
    com.zgc: debug
    #    org.springframework: debug
#数据库
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: 123456
  thymeleaf:
    cache: false

#    mode: HTML5
#Mybatis配置，驼峰功能
mybatis:
  #  configuration:
  #    map-underscore-to-camel-case: true
  mapper-locations: mapper/*.xml
  type-aliases-package: com.zgc.user.pojo

##thymeleaf相关配置spring.thymeleaf.encoding=UTF-8
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8090/eureka,http://127.0.0.1:8092/eureka
  instance:
    prefer-ip-address: true # 当其它服务获取地址时提供ip而不是hostname
    ip-address: 127.0.0.1
#    心跳不宜过高，过高会加重负载，服务续约的间隔，默认为30秒
    lease-renewal-interval-in-seconds: 30
#    服务失效时间，默认值90秒
    lease-expiration-duration-in-seconds: 90