server:
  port: 8090
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8090/eureka
#      指定IP地址
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1